FROM rust:1.70 as builder

WORKDIR /app
COPY . .

RUN cargo build --release

RUN ./target/release/ve ./docs/server.ve

FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    libc6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/docs ./docs
COPY --from=builder /app/Cargo.toml ./Cargo.toml

EXPOSE 8080

CMD ["./docs/build/program.exe"]
